server:
  port: 8013

spring:
  application:
    name: ms-socio-rest
  datasource:
    ##url: jdbc:sqlserver://MARCOS;databaseName=BDHOSPEDAJE
    url: jdbc:mysql://localhost:3306/DBCINEWEB
    ##driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
    username: root
    password: mysql

metodo:
  listarsocios: listarSocios
  obtenerSocio: obtenerSocio
  agregarSocio: agregarSocio

socio:
  codigo:
    idf0: 0
    idf1: 1
    idt3: -3
  mensaje:
    idf0: Operacion Exitosa
    idf1: No se obtuvieron resultados en la consulta.
    idt3: Error inesperado en el servicio.